create table if not exists bronze.magento.src_magento__sales_orders
(
    entity_id            string,
    increment_id         string,
    hl_parent_id         string,
    grand_total          float,
    total_paid           float,
    customer_email       string,
    sales_channel        string,
    coupon_code          string,
    coupon_rule_name     string,
    added_by_name        string,
    discount_description string,
    discount_amount      float,
    subtotal             float,
    status               string,
    shipping_description string,
    store_id             int,
    shipping_amount      float,
    tax_amount           float,
    base_currency_code   string,
    customer_firstname   string,
    customer_lastname    string,
    shipping_method      string,
    is_valid             int,
    used_coins           int,
    subtotal_incl_tax    float,
    shipping_tax_amount  float,
    products             string,
    created_at           string,
    send_date            string,
    sale_date            string,
    delivery_date        string,
    refund_date          string,
    updated_at           string,
    loaded_at            string
);