select
    so.entity_id                as "ENTITY_ID"
  , so.increment_id             as "INCREMENT_ID"
  , so.hl_parent_id             as "HL_PARENT_ID"
  , so.grand_total              as "GRAND_TOTAL"
  , so.total_paid               as "TOTAL_PAID"
  , so.customer_email           as "CUSTOMER_EMAIL"
  , so.sales_channel            as "SALES_CHANNEL"
  , so.coupon_code              as "COUPON_CODE"
  , so.coupon_rule_name         as "COUPON_RULE_NAME"
  , so.added_by_name            as "ADDED_BY_NAME"
  , so.discount_description     as "DISCOUNT_DESCRIPTION"
  , so.discount_amount          as "DISCOUNT_AMOUNT"
  , so.subtotal                 as "SUBTOTAL"
  , so.status                   as "STATUS"
  , so.shipping_description     as "SHIPPING_DESCRIPTION"
  , so.store_id                 as "STORE_ID"
  , so.shipping_amount          as "SHIPPING_AMOUNT"
  , so.tax_amount               as "TAX_AMOUNT"
  , so.base_currency_code       as "BASE_CURRENCY_CODE"
  , so.customer_firstname       as "CUSTOMER_FIRSTNAME"
  , so.customer_lastname        as "CUSTOMER_LASTNAME"
  , so.shipping_method          as "SHIPPING_METHOD"
  , so.is_valid                 as "IS_VALID"
  , so.used_coins               as "USED_COINS"
  , so.subtotal_incl_tax        as "SUBTOTAL_INCL_TAX"
  , so.shipping_tax_amount      as "SHIPPING_TAX_AMOUNT"
  , so.products                 as "PRODUCTS"
  , so.created_at               as "CREATED_AT"
  , so.send_date                as "SEND_DATE"
  , so.sale_date                as "SALE_DATE"
  , so.delivery_date            as "DELIVERY_DATE"
  , so.refund_date              as "REFUND_DATE"
  , so.updated_at               as "UPDATED_AT"
  , '{{ data_interval_start }}' as "LOADED_AT"
from magento.sales_order so
{% if not dag_run.conf.get('full_refresh') %}
    where so.updated_at >= '{{ data_interval_start  - macros.timedelta(hours=3) }}'
{% endif %}
